# Generated by Django 3.1.5 on 2021-01-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'Genre',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.URLField(max_length=400)),
                ('gif', models.URLField(max_length=400)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('length', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('synopsis', models.TextField(max_length=400)),
                ('iframe', models.TextField(max_length=5000)),
                ('url', models.URLField(max_length=400)),
                ('genres', models.ManyToManyField(db_table='movie-genre', related_name='movies', to='films.Genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'Movie',
                'ordering': ('-date_added',),
            },
        ),
    ]
