# Generated by Django 3.1.5 on 2021-02-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_genre_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='iframe',
        ),
    ]
