# Generated by Django 3.1.5 on 2021-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_movie_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='preview_url',
            field=models.URLField(default='https://www.youtube.com/embed/ldYJ916tqJY?autoplay=1&mute=0&start=168&end=198', max_length=400),
            preserve_default=False,
        ),
    ]
